### PR TITLE
Removed bloated KangarooTwelve implementation; replaced with one suit…

### PR DESCRIPTION
**Pull request by OhGodAPet**
…ed for only mining. This bugs me, so I did something about it.

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Huh?

**Comment by OhGodAPet** [comment]
The K12 implementation was massive and most of it was dead code.

**Comment by Noob-X** [comment]
Hi Wolf thanks for the PR.
Don't know whether it's just me but it doesn't build.

There's a hidden --test switch in case you want to test the algo. "./minerd --test"

**Comment by OhGodAPet** [comment]
> Hi Wolf thanks for the PR.
> Don't know whether it's just me but it doesn't build.
> 
> There's a hidden --test switch in case you want to test the algo. "./minerd --test"

Please include any compiler error(s)?

**Comment by OhGodAPet** [comment]
Sorry! Forgot to fix calls to k12_hash() - it no longer exists, having been replaced by k12(). The arguments also changed - this was remedied in the next patch!

**Comment by Noob-X** [comment]
Thanks, now it builds [with some minor warnings].
Unfortunately it doesn't hash correctly.
Quick way to test the algo is by using the --test switch.
I have tried pool mining and the --test switch to verify.

**Comment by OhGodAPet** [comment]
> Thanks, now it builds [with some minor warnings].
> Unfortunately it doesn't hash correctly.
> Quick way to test the algo is by using the --test switch.
> I have tried pool mining and the --test switch to verify.

Hey - found the issue and corrected it locally! I'm an idiot. Would you prefer me to fix up this PR, or just do a new one at this point?

**Comment by OhGodAPet** [comment]
I'll just clean this up and make a new fork + PR.

**Pull request closed without merging**
